website/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, IntegerField, PasswordField, SubmitField, EmailField, BooleanField
from wtforms.validators import EqualTo, Regexp, Email, Length, DataRequired, InputRequired


class RegistrationForm(FlaskForm):
    first_name = StringField("First Name", validators=[Length(min=3, max=10), InputRequired()])
    last_name = StringField("Last Name", validators=[Length(min=3, max=10), InputRequired()])
    email = EmailField("Email", validators=[Email(message="Use correct email"), DataRequired()])
    password = PasswordField("Password", validators=[Length(min=8, max=20), DataRequired()])
    confirm_password = PasswordField("Confirm Password", validators=[EqualTo("password"), DataRequired()])
    submit = SubmitField('Register')
    
    
class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[Email(message="Use correct email"), DataRequired()])
    password = PasswordField("Password", validators=[Length(min=8, max=20), DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')

website/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from os import path
from flask_login import LoginManager
import psycopg2
from . auth import *


def create_app():
    app = Flask(__name__)
    
    app.config['SQLALCHEMY_DATABASE_URI'] = "postgresql://postgres@benso7130@kedozi"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False 
    app.config['SECRET_KEY'] = 'Thisisforkedozirealestatecompany'
    
    bootstrap = Bootstrap(app)
    
    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    login_manager.login_message_category = "info"
    
    @login_manager.user_loader
    def load_user(email):
        
        #making the query into the database
        conn = psycopg2.connect(user = "postgres",password = "@benso7130",  host = "localhost",  database = "kedozi")
        cursor = conn.cursor()
        
        cursor.execute("SELECT * FROM users WHERE email=%s", (email,))
        user = cursor.fetchone()
        
        email = dict(session)['email']
        
        return user.email
    return app

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import login_required,logout_user, current_user,  login_user
import psycopg2 ##this is for connecting POSTGRES db with the python file.
from . forms import RegistrationForm, LoginForm
from flask_bcrypt import Bcrypt

auth = Blueprint("auth", __name__)
bcrypt = Bcrypt()

conn = psycopg2.connect(user = "postgres",password = "@benso7130",  host = "localhost",  database = "kedozi")
cursor = conn.cursor()

@auth.route('/register', methods=['GET','POST'], strict_slashes=False)
def register():
    if current_user.is_authenticated:
        return redirect(url_for("auth.dashboard"))
    form = RegistrationForm(request.form)
    
    # Get Form Values
    if request.method == 'POST' and form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data
        email = form.email.data
        password = form.password.data
        
        hashed_password = bcrypt.generate_password_hash(password,10).decode('utf-8')
        
        #check if the user email exists
        #searching the user by email
        conn = psycopg2.connect(user = "postgres",password = "#",  host = "localhost",  database = "kedozi")
        cursor = conn.cursor()
        
        #user = cursor.execute("SELECT * FROM users WHERE email=%s", (form.email,)).fetchone()
            
        cursor.execute("SELECT * FROM users WHERE email=%s", (email,))
        user_exists = cursor.fetchone()
        if not user_exists:
            try:
                # Execute Query
                cursor.execute("""INSERT INTO users (first_name,last_name, email, password) 
                        VALUES(%s,%s, %s, %s)""", 
                        (first_name, last_name, email,  hashed_password))
                #commit to the users database
                conn.commit()
                conn.close()
            except:
                    flash("Something is wrong. Please try again later", 'danger')
                    return redirect(url_for('register'))
            else:
                #close the cursor
                cursor.close()
                flash("Successful Registration, Login", "success")
            return redirect(url_for('auth.login'))
        else:
            flash("Your email has already being registered. Please Login","danger")
            cursor.close()
        return redirect(url_for('auth.login'))
    
    # get the request
    return render_template('register.html', form=form, user=current_user)

@auth.route('/login', methods=['GET', 'POST'], strict_slashes=False)
def login():
    if current_user.is_authenticated:
        return redirect(url_for("auth.dashboard"))
    form = LoginForm(request.form)
    
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password_candidate = form.password.data
        
        #search the user by email
        conn = psycopg2.connect(user = "postgres",password = "@benso7130",  host = "localhost",  database = "kedozi")
        cursor = conn.cursor()
        
        cursor.execute("SELECT * FROM users WHERE email=%s", (email, ))
        user = cursor.fetchone()
        #fname = results[1]
        #print(fname)
        
        #compare the passwords to check if they are similar
        if user:
            password = user[4]
            if bcrypt.check_password_hash(password, password_candidate):
                cursor.close()
                session['logged_in']= True
                session['email'] = email
                flash("Login successful","success")
                #login_user(user, remember=True)
                
                return redirect(url_for('auth.dashboard'))
                
            else:
                cursor.close()
                flash("INCORRECT password","danger")
                return render_template('login.html', form=form, title = 'login')
        else:
            # User email doesn't exist
            cursor.close()
            flash('EMAIL Does NOT exist, Please Register', 'danger')
        return redirect(url_for('auth.register'))
    #the login form
    return render_template('login.html', form=form, title='login', user=current_user)

@login_required
@auth.route('/dashboard', strict_slashes=False)
def dashboard():
    conn = psycopg2.connect(user = "postgres",password = "@benso7130",  host = "localhost",  database = "kedozi")
    cursor = conn.cursor()
    
    email = dict(session)['email']
    
    #cursor.execute("SELECT * FROM users WHERE email = %s",(email,))
    query1 = f"""SELECT first_name, last_name FROM users WHERE email='{email}'"""

    cursor.execute(query1)
    first_name = cursor.fetchone()

    cursor.close()
    #print(email)
    if first_name:
            return render_template('dashboard.html',
                                   first_name=first_name[0] + ' ' + first_name[1])
    else:
        print("Not available")
        
    return render_template('dashboard.html')


@auth.route('/more_information')
@login_required
def more_information():
    return "HELLO WORLD!!"

@login_required
@auth.route('/logout', strict_slashes=False)
#this functions logs out the user in session
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('views.home'))

def is_authenticated(self):
        return True       

website/views.py
from flask import Blueprint, render_template

views = Blueprint("views", __name__)


@views.route("/")
def home():
    return render_template("home.html")

@views.route("/about")
def about():
    return render_template("about.html")


@views.route('/listings')
def listings():
    return render_template('listings.html')

@views.route('/listing')
def listing():
    return render_template('listing.html')

website/templates/about.html
{% extends 'base.html' %}

{% block title %} | About {% endblock title %}
{% block content %} 
<section class="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">Our Services</h1>
                <p class="lead">We promise to provide you the most
                    Professional, Ethical and Informed Real Estate Services in the Industry!</p>
            </div>
        </div>
    </div>
</section>

 <!-- Breadcrumb -->
 <section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{url_for('views.home')}}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> About</li>
            </ol>
        </nav>
    </div>
</section>

<section id="about" class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>Do you know why we are the best home search?</h2>
                    <p class="lead" align ="justify">With the help of leadership and expertise, our company is able to
                        achieve great heights. Each member of our team is as committed to bring you the best 
                        possible experience as they are to make our company the best Real Estate Company in Kenya.
                    </p>
                    <img src='static\images\about.jpg' alt="">
                    <p class="mt-4" align="justify">In today’s challenging Real Estate market, your choice of Real
                        Estate Professional does matter! For a greater probability of success
                        you need a dedicated professional, one who can guide you through the process and be counted on
                        to protect your investment.
                        Get to know us, knowledgeable, results-oriented professional. Our most important
                        assets are
                        honesty and integrity. At Kedozi, our aim is to protect your interests in terms of housing and rental 
                        preferences. We sell houses to customers according to your requirements. We offer affordable housing.
                    </p>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="static\images\employee.jpg" alt="Seller of the month">
                    <div class="card-body">
                        <h5 class="card-title">Star of the Month</h5>
                        <h6 class="text-secondary">Yvonne Mwikali</h6>
                        <p class="card-text" align="justify">I can help you with the best deals in the property listings
                            and can accompany clients to property site and can discuss the conditions of sale. I an expert
                            in directing you towards the best property within your desired value. Over 5 years of 
                            negotiations experience, i go the distance to ensure that your best interests are protected.
                            For best and hifg quality homes, kindly contact kedozi real estate. We are here to give you
                            the best services. Our houses are found all over the country. We aim help people own a home
                            with no stress of price as our houses are affordable and accessible to both income classes.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

   <!-- Work -->
   <section id="work" class="bg-dark text-white text-center">
    <h3 class="display-4">We are here to serve you only the Best!</h3>
    <h5>Why still waiting? Start your search and grab an ideal home you Love</h5>
    <hr>
    <a href="{{url_for('views.listings')}}" class="btn btn-secondary text-white btn-lg">View Our Listings</a>
</section>

<section id="team" class="py-5">
    <div class="container">
        <h2 class="text-center">Our Team</h2>
        <div class="row text-center">
            <div class="col-md-4">
                <img src="static\images\nyanadua.jpg" alt="" class="rounded-circle mb-3">
                <h4>Hellen Mureithi</h4>
                <p class="text-success">
                    <i class="fas fa-award text-success mb-3"></i>Realtor</p>
                <hr>
                <p><i class="fas fa-phone"></i>+254798765432</p>
                <p><i class="fas fa-envelope-open"></i>Hellen@kedozirealestate.com</p>
            </div>
            <div class="col-md-4">
                <img src="static\images\agent.jpg" alt="" class="rounded-circle mb-3">
                <h4>John Mburu</h4>
                <p class="text-success">
                    <i class="fas fa-award text-success mb-3"></i>Realtor</p>
                <hr>
                <p><i class="fas fa-phone"></i>+254736789000</p>
                <p><i class="fas fa-envelope-open"></i>mburu@kedozirealestate.com</p>
            </div>
            <div class="col-md-4">
                <img src="static\images\final.jpg" alt="" class="rounded-circle mb-3">
                <h4>Lilian wambui</h4>
                <p class="text-success">
                    <i class="fas fa-award text-success mb-3"></i>Realtor</p>
                <hr>
                <p><i class="fas fa-phone"></i>+254712345678</p>
                <p><i class="fas fa-envelope-open"></i>wambui@kedozirealestate.com</p>
            </div>
    </div>
</section>
{% endblock content %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="GigRecommender">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
        <title>Kodezi Real Estate {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
        <!-- Lightbox -->
        <link rel="stylesheet" href="{{url_for('static',filename='css/lightbox.css')}}">
         <!-- Font Awesome -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/all.css')}}">
    </head>
    <body>

        <!--Navbars link-->
        {% include 'parts/navbars.html' %}

        <!--Top bar link-->
        {% include 'parts/topbar.html' %}

        <!--This is for the main content-->
        {% block content %}

        {% endblock content %}

        <!--This is for the footer page-->
        {% include 'parts/footer.html' %}
        

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
        <script src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
        <script src="{{url_for('static', filename='js/lightbox.min.js')}}"></script>

    </body>
</html>

website/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} | Dashboard {% endblock %}

{% block content %}
<!-- Alerts -->
{% include 'parts/alerts.html' %}

<section class="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">{{ first_name }} Dashboard </h1>
                <p class="lead">Manage all your inquired properties list here!</p>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{url_for('views.home')}}">
                        <i class="fas fa-home"></i>Home
                    </a>
                </li>
                <li class="breadcrumb-item active"> Dashboard</li>
            </ol>
        </nav>
    </div>
</section>
<section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>
                Welcome {{ first_name }}
          </h2>
                <p>Here are the property listings that you have inquired about</p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Property</th>
                <th></th>
              </tr>
            </thead>

        </div>
      </div>
    </div>
  </section>

{% endblock content %}

website/templates/home.html
{% extends 'base.html' %}

{% block title %} | Home {% endblock title %}
{% block content %} 
<!-- Alerts -->
{% include 'parts/alerts.html' %}
<section class="showcase">
    <div class="container text-center">
        <div class="home-search p-5">
            <div class="overlay p-5">
                <h1 class="display-4 mb-4">
                    Easy to Search the Property Here!
                </h1>
                <p class="lead">We value your Time and made your Property Search even Simpler.
                    See the Properties that only match your Conditions. 
                </p>
                <div class="search">
                    <form action="#">
                        <!-- Form Row 1 -->
                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label class="sr-only">Keywords</label>
                                <input type="text" name="keywords" class="form-control"
                                       placeholder="Try Keywords (garage, old, demolished etc)">
                            </div>
                            <div class="col-md-4 mb-3">
                                <label class="sr-only">City</label>
                                <input type="text" name="city" class="form-control" placeholder="City">
                            </div>

                            <div class="col-md-4 mb-3">
                                <label class="sr-only">Counties</label>
                                <select id="counties" name="county" class="form-control">
                                    <option selected="true" disabled="disabled">County (All)</option>
                                </select>
                            </div>
                        </div>
                        <!-- Form Row 2 -->
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label class="sr-only">Bedrooms</label>
                                <select name="bedrooms" class="form-control">
                                    <option selected="true" disabled="disabled">Bedrooms (All)</option>
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <select name="price" class="form-control" id="type">
                                    <option selected="true" disabled="disabled">Price (Max Price)</option>
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
                    </form>
            </div>
        </div>
    </div>
</section>
<!--Listings-->

<section id="listings" class="py-5">
    <div class="container">
        <h3 class="text-center mb-3">Latest Listings</h3>
        <div class="row">
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                    <img class="card-img-top" src="static\images\home-3.jpg" alt="no img">
                    <div class="card-img-overlay">
                        <h2>
                            <span class="badge badge-secondary text-white">$350000</span>
                        </h2>
                    </div>
                    <div class="listing-heading text-center">
                        <h4 class="text-primary">366, Kikuyu</h4>
                        <p>
                            <i class="fas fa-map-marker text-secondary"></i> Kikuyu,
                            Kiambu, 366
                        </p>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                        <div class="col-6">
                            <i class="fas fa-th-large"></i> Sqft:3200 </div>
                        <div class="col-6">
                            <i class="fas fa-car"></i> Garage: 2</div>
                    </div>
                    <div class="row py-2 text-secondary">
                        <div class="col-6">
                            <i class="fas fa-bed"></i> Bedrooms: 3</div>
                        <div class="col-6">
                            <i class="fas fa-bath"></i> Bathrooms: 2</div>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                        <div class="col-12">
                            <i class="fas fa-user"></i>Catherine Njeri</div>
                    </div>
                    <hr>
                    <a href="{{url_for('auth.more_information')}}" class="btn btn-primary btn-block">More
            
                        Info</a>
            
                </div>    
            </div>
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                    <img class="card-img-top" src="static\images\home-2.jpg" alt="no img">
                    <div class="card-img-overlay">
                        <h2>
                            <span class="badge badge-secondary text-white">$550000</span>
                        </h2>
                    </div>
                    <div class="listing-heading text-center">
                        <h4 class="text-primary">100, Kwambira</h4>
                        <p>
                            <i class="fas fa-map-marker text-secondary"></i>Kwambira, 
                            Limuru Town, 217
                        </p>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                        <div class="col-6">
                            <i class="fas fa-th-large"></i> Sqft:4000 </div>
                        <div class="col-6">
                            <i class="fas fa-car"></i> Garage: 2</div>
                    </div>
                    <div class="row py-2 text-secondary">
                        <div class="col-6">
                            <i class="fas fa-bed"></i> Bedrooms: 4</div>
                        <div class="col-6">
                            <i class="fas fa-bath"></i> Bathrooms: 2</div>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                        <div class="col-12">
                            <i class="fas fa-user"></i> John Mburu</div>
                    </div>
                    <hr>
                    <a href="{{url_for('auth.more_information')}}" class="btn btn-primary btn-block">More
            
                        Info</a>
            
                </div>    
            </div>
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                    <img class="card-img-top" src="static\images\home-11.jpg" alt="no img">
                    <div class="card-img-overlay">
                        <h2>
                            <span class="badge badge-secondary text-white">$550000</span>
                        </h2>
                    </div>
                    <div class="listing-heading text-center">
                        <h4 class="text-primary">168, Nthunguni</h4>
                        <p>
                            <i class="fas fa-map-marker text-secondary"></i> Mumbuni North,
                            Nthunguni, Machakos Town
                        </p>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                        <div class="col-6">
                            <i class="fas fa-th-large"></i> Sqft:3500 </div>
                        <div class="col-6">
                            <i class="fas fa-car"></i> Garage: 3</div>
                    </div>
                    <div class="row py-2 text-secondary">
                        <div class="col-6">
                            <i class="fas fa-bed"></i> Bedrooms: 5</div>
                        <div class="col-6">
                            <i class="fas fa-bath"></i> Bathrooms: 2</div>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                        <div class="col-12">
                            <i class="fas fa-user"></i>Yvonne Mwikali</div>
                    </div>
                    <hr>
                    <a href="{{url_for('auth.more_information')}}" class="btn btn-primary btn-block">More
            
                        Info</a>
            
                </div>    
            </div>
        </div>
        
    </div>

</section>

<section class="services" class="py-5 bg-secondary text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-4">
                <i class="fa fa-users fa-4x mr-4"></i>
                <hr>
                <h3>Customers</h3>
                <p>Our customers' satisfaction is the only focus of our mission and that's why we are here to serve
                    you only the best.The more we satisfy you, the more we grow!</p>
            </div>
            <div class="col-md-4">
                <i class="fas fa-home fa-4x mr-4"></i>
                <hr>
                <h3>Property Management</h3>
                <p>We list out the properties which may be one of the ideal home that you have dreamed for yours to
                    live in.It's not only about how you live, its about where you live.</p>
            </div>
            <div class="col-md-4">
                <i class="fa fa-handshake fa-4x mr-4"></i>
                <hr>
                <h3>Our Services</h3>
                <p>Our goal is to have customer service that is not just the best, but legendary. We consider each
                    customer as a family member who deserves nothing but the best service.</p>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

website/templates/login.html
{% extends 'base.html' %}
{% block title %} | Login {% endblock %}
{% block content %}

{% from "parts/formhelpers.html" import render_field %}

    <section id="login" class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h4>
                                <i class="fas fa-sign-in-alt"></i> Login</h4>
                        </div>
                        <div class="card-body">
                            <!-- Alerts-->
                            {% include 'parts/alerts.html' %}
                            <form method="POST">
                                {{ form.hidden_tag() }}
                                <div class="form-group">
                                    {{render_field(form.email, class_="form-control")}}
                                </div>
                    
                                <div class="form-group">
                                    {{render_field(form.password, class_="form-control")}}
                                </div>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="dropdownCheck">
                                    <label class="form-check-label" for="dropdownCheck">
                                      Remember me
                                    </label>
                                </div>

                                <input type="submit" value="Login" class="btn btn-secondary btn-block">
                                <p class="registered">Not yet Registered?<a href="{{url_for('auth.register')}}"> Register here!</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

website/templates/parts/footer.html
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> Kodezi Real Estate
  </footer>

website/templates/parts/navbars.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img class="logo" src="static\images\logo.jpg">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>

        {% if is_authenticated %}
        <a class="nav-link" href="{{url_for('auth.dashboard')}}">
            Welcome {{ first_name }} &nbsp;&nbsp;&nbsp;
            <i class="fa fa-address-card"></i> Dashboard
        </a>
        <a href="/logout" class="nav-link">
            <i class = "fas fa-sign-out-alt"></i>Logout
        </a>
        {% else %}

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <!--This is for the home page-->
                <li>
                    <a class="nav-link" href="{{url_for('views.home')}}">Home</a>
                </li>
                <li>
                    <a class="nav-link" href="{{url_for('views.about')}}">About</a>
                </li>
                <!--This is for the property listings page-->
                <li>
                    <a class="nav-link" href="{{url_for('views.listings')}}">Property Listings</a>
                </li>
            </ul>
            <!--This is for user registration and Login-->
            <ul class="navbar-nav ml-auto">
                <a class="nav-link" href="{{url_for('auth.register')}}">
                    <i class="fas fa-user-plus"></i> Register
                </a>
                <a class="nav-link" href="{{url_for('auth.login')}}">
                    <i class="fas fa-sign-in-alt"></i>Login
                </a>
                <!-- Default dropright button -->
            </ul>
        </div>
        {% endif %}     
    </div>
</nav>